name: Kotlin Lint

on:
  pull_request:
    branches:
      - develop
      - main
    paths:
      - 'app/src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Lint Kotlin code
        run: ./gradlew ktlintCheck
